# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVVM-C Template' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MVVM-C Template

  target 'MVVM-C TemplateTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MVVM-C TemplateUITests' do
    # Pods for testing
  end

end
